# Uses travis-yaml to check your .travis.yml config.
# http://lint.travis-ci.org/

language: java
# command to be execute
# case single line
# script: [command]
# case multi-line
script:
  - ./gradlew check
